# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  npm-registry-new:
    type: npm-registry
    url: "https://npm.pkg.github.com"
    username: ${{secrets.MY_ARTIFACTORY_PASSWORD}}
    password: ${{secrets.MY_ARTIFACTORY_USERNAME}}
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: cron
      cronjob: "*/1 0 * * *"
    ignore:
      - dependency-name: "moment"
    groups:
      everything-npm:
        patterns:
          - "*"
    commit-message:
      prefix: "dependabot made it!!!"
      include: scope
    assignees:
      - williamt-infomagnus
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: cron
      cronjob: "*/1 0 * * *"
    groups:
      everything-python:
        patterns:
          - "*"
    assignees:
      - williamt-infomagnus

    
  
